apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DB_USER: cm9vdA==          # "root" em base64
  DB_PASSWORD:               # senha em base64 (ex: "123456" -> MTIzNDU2)