apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer   # cria um endpoint público na AWS
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000